# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

seed: 42

models:
  separate: False
  policy:
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: features_extractor
        input: permute(OBSERVATIONS["image"], (0, 3, 1, 2))
        layers:
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 4, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - flatten
          - linear: 512
          - linear: 64
        activations: [relu, relu, relu, null, elu, elu]
      - name: state_encoder
        input: concatenate([OBSERVATIONS["joint_pos"], OBSERVATIONS["joint_vel"], OBSERVATIONS["object_position"], OBSERVATIONS["target_object_position"], OBSERVATIONS["actions"]])
        layers: [128, 64]
        activations: elu
      - name: net
        input: concatenate([features_extractor, state_encoder])
        layers: [256, 128]
        activations: elu
    output: ACTIONS
  value:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: features_extractor
        input: permute(OBSERVATIONS["image"], (0, 3, 1, 2))
        layers:
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 4, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - flatten
          - linear: 512
          - linear: 64
        activations: [relu, relu, relu, null, elu, elu]
      - name: state_encoder
        input: concatenate([OBSERVATIONS["joint_pos"], OBSERVATIONS["joint_vel"], OBSERVATIONS["object_position"], OBSERVATIONS["target_object_position"], OBSERVATIONS["actions"]])
        layers: [128, 64]
        activations: elu
      - name: net
        input: concatenate([features_extractor, state_encoder])
        layers: [256, 128]
        activations: elu
    output: ONE

memory:
  class: RandomMemory
  memory_size: -1

agent:
  class: PPO
  rollouts: 24
  learning_epochs: 5
  mini_batches: 4
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 6.0e-5
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  state_preprocessor: null
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 0.5
  ratio_clip: 0.15
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.0005
  value_loss_scale: 2.0
  kl_threshold: 0.02
  rewards_shaper_scale: 0.01
  time_limit_bootstrap: False
  experiment:
    directory: "franka_lift_camera_fusion"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto

trainer:
  class: SequentialTrainer
  timesteps: 360000
  environment_info: log
